# To compile release version or debug version
COMPILE_VERSION = release # debug 
#COMPILE_VERSION = debug 

# If set to 1, then use cpu only
CPU_ONLY := 1

# If set to 1, then compile realtime analyse server
REALTIME_SERVER := 0

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
#CUSTOM_CXX := /home/fyx/.local/local/gcc-4.8.3/bin/g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them (up to CUDA 5.5 compatible).
# For the latest architecture, you need to install CUDA >= 6.0 and uncomment
# the *_50 lines below.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		#-gencode arch=compute_50,code=sm_50 \
		#-gencode arch=compute_50,code=compute_50

# BLAS choice:
# cblas for CBLAS (default)
# mkl for MKL
BLAS := mkl
BLAS_INCLUDE := /home/fyx/.local/intel/mkl/include
BLAS_LIB := /home/fyx/.local/intel/mkl/lib/intel64 /home/fyx/.local/intel/lib/intel64

# ZeroMQ 
ZMQ_INCLUDE := /home/fyx/.local/dependence/zeromq/include
ZMQ_LIB := /home/fyx/.local/dependence/zeromq/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
# PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# PYTHON_INCLUDE := $(HOME)/anaconda/include \
		# $(HOME)/anaconda/include/python2.7 \
		# $(HOME)/anaconda/lib/python2.7/site-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
# PYTHON_LIB := /usr/lib
# PYTHON_LIB := $(HOME)/anaconda/lib

# OpenCV Config
# OPENCV_INCLUDE := /home/fyx/.local/dependence/opencv/include
# OPENCV_LIB := /home/fyx/.local/dependence/opencv/lib

# BOOST CONFIG
# BOOST_INCLUDE := /home/fyx/.local/dependence/boost/include
# BOOST_LIB := /home/fyx/.local/dependence/boost/lib

# level db
# LEVELDB_INCLUDE := /home/fyx/.local/dependence/leveldb/include
# LEVELDB_LIB := /home/fyx/.local/dependence/leveldb

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(BLAS_INCLUDE) $(ZMQ_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(BLAS_LIB) $(ZMQ_LIB) /usr/local/lib /usr/lib 


